spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/pharmacy_db
spring.datasource.username=root
spring.datasource.password=276100fuck1234
spring.servlet.multipart.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
